### ISSUE TITLE
Support Pause/Resume or Stop/Restart in Corb. 

### ISSUE THREAD

**Issue by bbandlamudi** [marklogic/corb2#15]

**Comment by hansenmc** [comment]
What about implementing something like the Java Service Wrapper [wrapper.commandfile](https://wrapper.tanukisoftware.com/doc/english/prop-commandfile.html), in which CoRB would at regular intervals look for the existence of a commandfile and use the contents to control status (pause/resume/stop/restart)?

It might also be a convenient way to adjust, at runtime, other properties/settings such [as THREAD-COUNT (issue #14 )](https://github.com/marklogic/corb2/issues/14) if it were expected to be a properties file.

It could be added as a top-tier properties set, so that the order of precedence for CoRB getProperty() would be: 
  1. commandFile properties
  1. System.properties
  1. commandline properties
  1. OPTIONS-FILE

**Comment by hansenmc** [comment]
Or could simply watch the options file, but would need to evaluate whether/when any properties should be overridden if they had originally been set as system or commandline props and are now changed in the OPTIONS-FILE at runtime.

**Comment by bbandlamudi** [comment]
Options file can be tricky as it is quite common to pass the parameters via java system args. I remember we have discussed about command file earlier and I believe we can implement it with out adding a new dependency.
