### ISSUE TITLE
Best way to distribute a job?

### ISSUE THREAD

**Issue by RobertSzkutak** [marklogic/corb2#40]
In some testing it doesn't seem like CORB supports load balancers? We experienced that CORB gets EOF errors when sent through a load balancer but works fine when sent directly to a host. Further, it seems that only way to distribute CORB's load is to run multiple instances of it and point each instance to separate hosts. Is there a better way?

**Comment by hansenmc** [comment]
Is the load balancer configured for session affinity for the XCC port used?

Can you post a stack trace?

[Using a Load Balancer or Proxy Server with an XCC Application](http://docs.marklogic.com/7.0/guide/xcc/concepts#id_85598)
-
When you use a load balancer, it is possible for requests from your application to MarkLogic Server to be routed to different hosts, even within the same session. This has no effect on most interactions with MarkLogic Server, but queries evaluated in the context of the same multi-statement transaction need to be routed to the same host within your MarkLogic cluster. This consistent routing through a load balancer is called session affinity.

**Comment by bbandlamudi** [comment]
Hi Robert, 
Please subscribe to mailing list http://developer.marklogic.com/mailman/listinfo/corb2. We have many members subscribed and it is easier to get answers or share experiences. 

We have been using CORB against load balancers (F5) for a while in several projects. I have seen EOF errors while going through a proxy in different networks, but this was usually because of dropped connections. Please note that CORB by itself doesn't open sockets, but relies on marklogic XCC API. Is your XCC jar version compatible with Mark Logic server? Also, try the latest XCC if possible - which may have some fixes. In most cases EOF errors are due to network or configuration related issues. 

Thanks,
Bhagat

**Comment by RobertSzkutak** [comment]
Thanks, this was helpful!
